# Generated by Django 4.2.7 on 2026-08-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('stem', models.TextField()),
                ('options', models.JSONField()),
                ('answer_index', models.IntegerField()),
                ('answer_source', models.CharField(choices=[('official', 'Official MPSC Key'), ('derived', 'AI Extracted')], default='derived', max_length=20)),
                ('paper_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(default='gk', max_length=100)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('has_diagram', models.BooleanField(default=False)),
                ('diagram_image', models.CharField(blank=True, max_length=500, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('ambiguous', 'Ambiguous')], db_index=True, default='pending', max_length=20)),
                ('marked_answer', models.CharField(max_length=1)),
                ('model_answer', models.CharField(max_length=1)),
                ('your_decision', models.CharField(blank=True, max_length=1, null=True)),
                ('your_reasoning', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='questions.question')),
            ],
            options={
                'ordering': ['status', '-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['paper_id', 'topic'], name='questions_q_paper_i_8e98d2_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['answer_source'], name='questions_q_answer__cb2c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationresult',
            index=models.Index(fields=['status'], name='questions_v_status_7b3e79_idx'),
        ),
    ]
