# Generated by Django 4.2.7 on 2026-08-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
