# Generated by Django 4.2.7 on 2026-08-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=255)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('paper_number', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_subject', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
